name: main

on:
  push:
    branches: [ main, test-me-* ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jontindal/riscv-arch-test:latest
      options: --entrypoint /bin/bash

    steps:
    - name: Mark Github workspace as safe
      run: git config --system --add safe.directory "${GITHUB_WORKSPACE}"
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          version: "0.7.2"
    - name: Install package
      run: |
        uv venv --python 3.10
        uv sync --all-extras --dev
    - name: Run pre-commit
      run: |
        uv run pre-commit run --all-files
    - name: Run pytests
      run: |
        uv run pytest
    - name: Run RISCOF
      working-directory: ./riscof
      run: |
        sed -i '/docker=true/d' config.ini
        uv run riscof --verbose info arch-test --clone
        uv run riscof run --config=config.ini --suite=riscv-arch-test/riscv-test-suite/ --env=riscv-arch-test/riscv-test-suite/env --no-browser
    - name: Run firmware examples
      working-directory: ./firmware
      run: |
        sed -i 's/PREFIX = riscv32-unknown-elf-/PREFIX = riscv-none-elf-/g' Makefile
        TARGET=basic_asm make
        TARGET=basic_c make
        uv run pyriscv build/basic_asm.bin
        uv run pyriscv build/basic_c.bin
